name: "RCBus YMF-262 build"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    paths:
      - '*.kicad_sch'
      - '*.kicad_pcb'
      - '*.kibot.yaml'
      - '.github/workflows/kibot.yml'
  pull_request:
    paths:
      - '*.kicad_sch'
      - '*.kicad_pcb'
      - '*.kibot.yaml'
      - '.github/workflows/kibot.yml'
  repository_dispatch:
    types: [run_qs]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        # So we can run a diff between last 2 changes
        fetch-depth: '0'
        submodules: recursive
    - name: Get next version
      uses: reecetech/version-increment@2024.10.1
      id: version
      with:
        scheme: semver
        increment: patch
    - name: Save info in environment variables
      run: |
        echo "VERSION=${{ steps.version.outputs.version }}" >> $GITHUB_ENV
    - name: Quick Start
      uses: INTI-CMNB/KiBot@v2_k9
      with:
        dir: Generated
    - name: Upload release files
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          Generated/**
    - name: Retrieve results
      uses: actions/upload-artifact@v6
      with:
        name: Automatic_outputs
        path: Generated

  # This step is to upload the results to another repo (web pages)
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v6

    - name: Retrieve results
      uses: actions/download-artifact@v7
      with:
        name: Automatic_outputs
        path: Generated

    - name: Disable Jekyll
      # Jekyll will filter the KiRi folders
      run: |
        touch Generated/.nojekyll

    - name: Deploy navigate results
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: main
        folder: Generated
        repository-name: electrified/rcbus-opl3-site
        token: ${{ secrets.TOKEN }}
